# Site settings
title:       iostrek
author:      Masha Safina
description: ":rocket:"
baseurl:     "" 
url:         "https://iostrek.github.io" 

# Social Links
email:            getiostrek@gmail.com
twitter_username: iostrek
github_username:  iostrek

# Build settings
markdown: kramdown
permalink: pretty

future: true
